# make sure you update CONFIG_PATH in mloop_multishot.py and
# plot_mloop_results.py before running the optimization
# so that it uses the corrent config file

[COMPILATION]
mock = false

[ANALYSIS]
cost_key = ["cloud_position_analysis", "Cloud Displacement (um)"]
maximize = false
ignore_bad = false # true
analysislib_console_log_level = 20
analysislib_file_log_level = 10
groups = ["Cs_MOT_params"]

[MLOOP]
num_training_runs = 20
max_num_runs_without_better_params = 20
max_num_runs = 80
trust_region = 0.99
cost_has_noise = true
no_delay = false
visualisations = false
controller_type = "gaussian_process"
console_log_level = 0

# Bias X
[MLOOP_PARAMS.Cs_MOT_params.Bias_X_HH_CsMOT]
global_name = 'Bias_X_HH_CsMOT'
min = 0
max = 3
start = 1.5

# Bias Z
[MLOOP_PARAMS.Cs_MOT_params.Bias_Z_HH_CsMOT]
global_name = 'Bias_Z_HH_CsMOT'
min = -6
max = 0
start = -3

# Bias Y
[MLOOP_PARAMS.Cs_MOT_params.Bias_Y_HH_CsMOT]
global_name = 'Bias_Y_HH_CsMOT'
min = -6
max = 0
start = -3